name: Run Renovate

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug  # Add this line to enable debug logging
          additionalConfig: "--autodiscover"
